theme: jekyll-theme-cayman

title : Opensoftlab LUNA™ Agile
teaser : "/assets/images/opensoftlab_logo.jpg"
<center><img data-action="zoom" src='{{ "/assets/images/opensoftlab_logo.jpg" | relative_url }}' alt='absolute'></center>
